name        = "Colemak-Lafayette"
name8       = "ColemakL"
locale      = "fr"
variant     = "Colemak-Lafayette"
description = "French (Colemak-Lafayette)"
url         = "https://github.com/Nuclear-Squid/ergol"
geometry    = "ERGO"
version     = "0.99.3"

# # SFU  = 1.21% / 0.81%
# base = '''
# ╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
# ┆ ~   ┃ € ‚ │ @ ‘ │ # ’ │ $   │ % ‰ ┃ ^   │ &   │ *   │ «   │ »   ┃ _ – ┆ + ± ┆
# ┆ `   ┃ 1 „ │ 2 “ │ 3 ” │ 4   │ 5   ┃ 6   │ 7   │ 8 § │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≠ ┆
# ╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
# ·     ┃ Q   │ W   │ F   │ P   │ B   ┃ J   │ L   │ O   │ ! ¡ │ Y   ┃ {   ┆ }   ┆
# ·     ┃   â │     │     │     │     ┃     │   ô │   œ │***¨ │   û ┃ [   ┆ ]   ┆
# ·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
# ·     ┃ A   │ R   │ S   │ T   │ G   ┃ M   │ N   │ E   │ I   │ U   ┃ "   ┆ |   ┆
# ·     ┃   à │   é │   ß │     │     ┃     │   ê │   è │     │   ù ┃ '   ┆ \   ┆
# ╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
# ┆ >   ┃ Z   │ X   │ C   │ D   │ V   ┃ K   │ H   │ ? ¿ │ ; • │ :   ┃           ·
# ┆ <   ┃     │     │   ç │     │     ┃     │   î │ - — │ , · │ . … ┃           ·
# ╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
# '''

# # SFU  = 1.21% / 0.81%
# base = '''
# ╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
# ┆ ~   ┃ € ‚ │ @ ‘ │ # ’ │ $   │ % ‰ ┃ ^   │ &   │ *   │ «   │ »   ┃ _ – ┆ + ± ┆
# ┆ `   ┃ 1 „ │ 2 “ │ 3 ” │ 4   │ 5   ┃ 6   │ 7   │ 8 § │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≠ ┆
# ╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
# ·     ┃ Q   │ W   │ F   │ P   │ B   ┃ K   │ L   │ O   │ ! ¡ │ Y   ┃ {   ┆ }   ┆
# ·     ┃   â │     │     │     │     ┃     │   ô │   œ │***¨ │   û ┃ [   ┆ ]   ┆
# ·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
# ·     ┃ A   │ R   │ S   │ T   │ D   ┃ M   │ N   │ E   │ I   │ U   ┃ "   ┆ |   ┆
# ·     ┃   à │   é │   ß │     │     ┃     │   ê │   è │     │   ù ┃ '   ┆ \   ┆
# ╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
# ┆ >   ┃ Z   │ X   │ C   │ V   │ G   ┃ J   │ H   │ ? ¿ │ ; • │ :   ┃           ·
# ┆ <   ┃     │     │   ç │     │     ┃     │   î │ - — │ , · │ . … ┃           ·
# ╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
# '''

# # SFU = 1.46% / 1.12%
# base = '''
# ╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
# ┆ ~   ┃ € ‚ │ @ ‘ │ # ’ │ $   │ % ‰ ┃ ^   │ &   │ *   │ «   │ »   ┃ _ – ┆ + ± ┆
# ┆ `   ┃ 1 „ │ 2 “ │ 3 ” │ 4   │ 5   ┃ 6   │ 7   │ 8 § │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≠ ┆
# ╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
# ·     ┃ Q   │ L   │ W   │ P   │ B   ┃ K   │ F   │ O   │ ! ¡ │ Y   ┃ {   ┆ }   ┆
# ·     ┃   â │     │     │     │     ┃     │   ô │   œ │***¨ │   û ┃ [   ┆ ]   ┆
# ·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
# ·     ┃ A   │ R   │ S   │ T   │ D   ┃ M   │ U   │ E   │ I   │ N   ┃ "   ┆ |   ┆
# ·     ┃   à │   é │   ß │     │     ┃     │   ê │   è │     │   ù ┃ '   ┆ \   ┆
# ╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
# ┆ >   ┃ Z   │ X   │ C   │ V   │ G   ┃ J   │ H   │ ? ¿ │ ; • │ :   ┃           ·
# ┆ <   ┃     │     │   ç │     │     ┃     │   î │ - — │ , · │ . … ┃           ·
# ╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
# '''

# Turbo-Nuke test
base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ € ‚ │ @ ‘ │ # ’ │ $   │ % ‰ ┃ ^   │ &   │ *   │ «   │ »   ┃ _ – ┆ + ± ┆
┆ `   ┃ 1 „ │ 2 “ │ 3 ” │ 4   │ 5   ┃ 6   │ 7   │ 8 § │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≠ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ L   │ Y   │ P   │ B   ┃ K   │ F   │ O   │ ! ¡ │ W   ┃ {   ┆ }   ┆
·     ┃   â │     │     │     │     ┃     │   ô │   œ │***¨ │   û ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ N   │ S   │ T   │ D   ┃ M   │ U   │ E   │ I   │ R   ┃ "   ┆ |   ┆
·     ┃   à │   é │   ß │     │     ┃     │   ê │   è │     │   ù ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ Z   │ X   │ C   │ V   │ G   ┃ J   │ H   │ ? ¿ │ ; • │ :   ┃           ·
┆ <   ┃     │     │   ç │     │     ┃     │   î │ - — │ , · │ . … ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

# # SFU = 1.46% / 1.47%
# base = '''
# ╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
# ┆ ~   ┃ € ‚ │ @ ‘ │ # ’ │ $   │ % ‰ ┃ ^   │ &   │ *   │ «   │ »   ┃ _ – ┆ + ± ┆
# ┆ `   ┃ 1 „ │ 2 “ │ 3 ” │ 4   │ 5   ┃ 6   │ 7   │ 8 § │ 9 ¶ │ 0 ° ┃ / ÷ ┆ = ≠ ┆
# ╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
# ·     ┃ Q   │ L   │ W   │ P   │ B   ┃ K   │ F   │ O   │ ! ¡ │ Y   ┃ {   ┆ }   ┆
# ·     ┃     │     │     │     │     ┃     │   ô │   œ │***¨ │     ┃ [   ┆ ]   ┆
# ·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
# ·     ┃ A   │ R   │ S   │ T   │ D   ┃ M   │ U   │ E   │ I   │ N   ┃ "   ┆ |   ┆
# ·     ┃   à │   â │   ß │     │     ┃   ê │   é │   è │   î │   ñ ┃ '   ┆ \   ┆
# ╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
# ┆ >   ┃ Z   │ X   │ C   │ V   │ G   ┃ J   │ H   │ ? ¿ │ ; • │ :   ┃           ·
# ┆ <   ┃     │     │   ç │     │     ┃     │   ù │ - — │ , · │ . … ┃           ·
# ╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
# '''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │   ≤ │   ≥ │  *¤ │   ‰ ┃  *^ │  *µ │   × │  *´ │  *` ┃     ┆     ┆
·     ┃   @ │   < │   > │   $ │   % ┃   ^ │   & │   * │   ' │   ` ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │   ⁽ │   ⁾ │     │   ≠ ┃  */ │   ± │   — │   ÷ │  *¨ ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   \ │   + │   - │   / │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │     │     │   – │     ┃   ¦ │   ¬ │  *¸ │     │     ┃           ·
┆     ┃   ~ │   [ │   ] │   _ │   # ┃   | │   ! │   ; │   : │   ? ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION MARK
